version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    networks:
      - app
    ports:
      - 8080:8080

  webapp:
    networks:
      - app
    command: npm run watch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      ENV_NAME: dev
    ports:
      - 3000:3000
    depends_on:
      - postgres

networks:
  app:

volumes:
  build:
