version: "3.4"

x-common: &common
  image: app:local
  labels:
    com.app: app
  networks:
    - app
  volumes:
    - build:/app/build/

services:
  builder:
    volumes:
      - build:/app/build/
      - .:/app:delegated
    <<: *common
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "app:local"
        - "app:${BRANCH_NAME:-ignore}"
    container_name: app-builder
    working_dir: /app
    command:
      [
        sh,
        -c,
        "rm -rf ./build/* && ./node_modules/.bin/tsc -w --pretty --skipLibCheck",
      ]

  js:
    image: app:local
    container_name: main
    env_file:
      - .env.dist
    depends_on:
      - postgres
      - redis
    networks:
      - app

  webapp:
    <<: *common
    working_dir: /app/build
    container_name: webapp
    command:
      [
        sh,
        -c,
        "node-dev --inspect=0.0.0.0 -r source-map-support/register ./src/index.js",
      ]
    hostname: webapp
    depends_on:
      - postgres
      - redis
    ports:
      - "1337:1337"
      - "4000:4000"
      - "9229:9229"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: "redis"
    ports:
      - "6379:6379"
    networks:
      - app

networks:
  app:

volumes:
  build:
